export const tokens = {
  color: {
    background: '#F7F2E8',
    surfaceElevated: '#FFFCF6',
    surfaceSunken: '#F0E8DA',
    textPrimary: '#1D1C19',
    textSecondary: '#6F685C',
    textTertiary: '#958C7C',
    border: '#E5DCCB',
    actionPrimary: '#171717',
    actionPrimaryContrast: '#FFFCF6',
    accent: '#B58C4A',
    accentContrast: '#1D1C19',
    accentSoft: '#DCC89D',
    success: '#68755F',
    warning: '#B58C4A',
    danger: '#C65D47',
  },
  space: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 32,
    8: 48,
  },
  radius: {
    small: 12,
    medium: 18,
    large: 30,
    round: 999,
  },
  type: {
    family: {
      display: 'Newsreader',
      interface: 'Inter',
    },
    size: {
      eyebrow: 12,
      metadata: 13,
      small: 14,
      body: 16,
      lede: 17,
      status: 18,
      heading: 22,
      title: 32,
      displayCompact: 34,
      display: 40,
    },
    lineHeight: {
      eyebrow: 16,
      metadata: 18,
      small: 20,
      body: 24,
      lede: 27,
      status: 24,
      heading: 29,
      title: 38,
      displayCompact: 40,
      display: 45,
    },
    weight: {
      regular: '400',
      medium: '600',
      bold: '700',
    },
  },
  size: {
    minimumTouchTarget: 44,
    primaryButtonHeight: 52,
    contentMaxWidth: 720,
  },
  shadow: {
    elevated: {
      color: '#171717',
      opacity: 0.1,
      radius: 16,
      offsetY: 6,
    },
  },
  motion: {
    fast: 180,
    standard: 220,
    ritual: 360,
  },
} as const;

export type DesignTokens = typeof tokens;

export function tokensToCssVariables(): Record<string, string> {
  return {
    '--ao-color-background': tokens.color.background,
    '--ao-color-surface-elevated': tokens.color.surfaceElevated,
    '--ao-color-surface-sunken': tokens.color.surfaceSunken,
    '--ao-color-text-primary': tokens.color.textPrimary,
    '--ao-color-text-secondary': tokens.color.textSecondary,
    '--ao-color-text-tertiary': tokens.color.textTertiary,
    '--ao-color-border': tokens.color.border,
    '--ao-color-action-primary': tokens.color.actionPrimary,
    '--ao-color-action-primary-contrast': tokens.color.actionPrimaryContrast,
    '--ao-color-accent': tokens.color.accent,
    '--ao-color-accent-contrast': tokens.color.accentContrast,
    '--ao-color-accent-soft': tokens.color.accentSoft,
    '--ao-color-success': tokens.color.success,
    '--ao-color-warning': tokens.color.warning,
    '--ao-color-danger': tokens.color.danger,
    '--ao-space-1': `${tokens.space[1]}px`,
    '--ao-space-2': `${tokens.space[2]}px`,
    '--ao-space-3': `${tokens.space[3]}px`,
    '--ao-space-4': `${tokens.space[4]}px`,
    '--ao-space-5': `${tokens.space[5]}px`,
    '--ao-space-6': `${tokens.space[6]}px`,
    '--ao-space-7': `${tokens.space[7]}px`,
    '--ao-space-8': `${tokens.space[8]}px`,
    '--ao-radius-small': `${tokens.radius.small}px`,
    '--ao-radius-medium': `${tokens.radius.medium}px`,
    '--ao-radius-large': `${tokens.radius.large}px`,
    '--ao-radius-round': `${tokens.radius.round}px`,
    '--ao-type-family-display': `${tokens.type.family.display}, 'Noto Serif JP', Georgia, serif`,
    '--ao-type-family-interface': `${tokens.type.family.interface}, 'Noto Sans JP', ui-sans-serif, system-ui, sans-serif`,
    '--ao-type-size-eyebrow': `${tokens.type.size.eyebrow}px`,
    '--ao-type-size-metadata': `${tokens.type.size.metadata}px`,
    '--ao-type-size-small': `${tokens.type.size.small}px`,
    '--ao-type-size-body': `${tokens.type.size.body}px`,
    '--ao-type-size-lede': `${tokens.type.size.lede}px`,
    '--ao-type-size-status': `${tokens.type.size.status}px`,
    '--ao-type-size-heading': `${tokens.type.size.heading}px`,
    '--ao-type-size-title': `${tokens.type.size.title}px`,
    '--ao-type-size-display-compact': `${tokens.type.size.displayCompact}px`,
    '--ao-type-size-display': `${tokens.type.size.display}px`,
    '--ao-type-line-height-eyebrow': `${tokens.type.lineHeight.eyebrow}px`,
    '--ao-type-line-height-metadata': `${tokens.type.lineHeight.metadata}px`,
    '--ao-type-line-height-small': `${tokens.type.lineHeight.small}px`,
    '--ao-type-line-height-body': `${tokens.type.lineHeight.body}px`,
    '--ao-type-line-height-lede': `${tokens.type.lineHeight.lede}px`,
    '--ao-type-line-height-status': `${tokens.type.lineHeight.status}px`,
    '--ao-type-line-height-heading': `${tokens.type.lineHeight.heading}px`,
    '--ao-type-line-height-title': `${tokens.type.lineHeight.title}px`,
    '--ao-type-line-height-display-compact': `${tokens.type.lineHeight.displayCompact}px`,
    '--ao-type-line-height-display': `${tokens.type.lineHeight.display}px`,
    '--ao-type-weight-regular': tokens.type.weight.regular,
    '--ao-type-weight-medium': tokens.type.weight.medium,
    '--ao-type-weight-bold': tokens.type.weight.bold,
    '--ao-size-minimum-touch-target': `${tokens.size.minimumTouchTarget}px`,
    '--ao-size-primary-button-height': `${tokens.size.primaryButtonHeight}px`,
    '--ao-content-max-width': `${tokens.size.contentMaxWidth}px`,
    '--ao-shadow-elevated': `0 ${tokens.shadow.elevated.offsetY}px ${tokens.shadow.elevated.radius}px color-mix(in srgb, ${tokens.shadow.elevated.color} ${tokens.shadow.elevated.opacity * 100}%, transparent)`,
    '--ao-motion-fast': `${tokens.motion.fast}ms`,
    '--ao-motion-standard': `${tokens.motion.standard}ms`,
    '--ao-motion-ritual': `${tokens.motion.ritual}ms`,
  };
}
